name: Deploy to Main Branch

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 确保能够获取完整的git历史

      - name: Set up Git config
        run: |
          git config --global user.name 'build-bot'
          git config --global user.email 'build@apihub.bot'

      - name: Run build script
        run: |
          chmod +x ./build/build.sh
          ./build/build.sh

      - name: Commit files
        run: |
          git add .
          git commit -m "Automated build and deploy to main branch" || echo "No changes to commit"

      - name: Push to main
        run: |
          git checkout -b build
          git add .
          git commit -m "build"
          git checkout main
          git merge build
          git push -u origin main

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          token: ${{ secrets.APIHUB_GITHUB_TOKEN }}
          pr_title: "Automated Deployment to Main"
          pr_body: "Auto-generated Pull Request from GitHub Actions"
          destination_branch: "main"
          source_branch: "new-branch-for-main"