name: Build

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v2

      - name: Set up Git config
        run: |
          git config --global user.name 'ApiHub'
          git config --global user.email 'build@ApiHub.bot'

      - name: Run build script
        run: |
          chmod +x ./build/build.sh
          ./build/build.sh

      - name: Commit files
        run: |
          git add .
          git commit -m "Automated build and deploy to main branch" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main