name: Auto Deploy to Main Branch

on:
  push:
    branches: [ dev ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 检出 dev 分支的代码
    - name: Checkout Dev Branch
      uses: actions/checkout@v2
      with:
        ref: dev

    # 运行您的 build.sh 脚本
    - name: Run Build Script
      run: chmod +x ./build/build.sh && ./build/build.sh

    # 配置 Git 用户信息
    - name: Setup Git Configuration
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    # 提交更改到临时分支
    - name: Commit changes
      run: |
        git add .
        git checkout -b "build"
        git commit -m "Deploy changes from dev to main"

    # 推送更改到远程 main 分支
    - name: Push Changes to Main Branch
      uses: ad-m/github-push-action@master
      with:
        branch: build
        github_token: ${{ secrets.GITHUB_TOKEN }}