name: Build and Deploy

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 检出 dev 分支的代码
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: dev

      # 设置 git 配置
      - name: Set up Git
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@example.com'

      # 运行 build.sh 脚本
      - name: Run build script
        run: bash ./build/build.sh

      # 提交更改到 main 分支
      - name: Commit and push to main
        run: |
          git checkout -b main
          git add -A
          git commit -m "Automated build and commit"
          git push --force https://${{ secrets.APIHUB_GITHUB_TOKEN }}@github.com/apiwind/apihub main