name: Auto Deploy to Main Branch

on:
  push:
    branches: [ dev ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 检出 dev 分支的代码
    - name: Checkout Dev Branch
      uses: actions/checkout@v2
      with:
        ref: dev

    # 运行您的 build.sh 脚本
    - name: Run Build Script
      run: chmod +x ./build/build.sh && ./build/build.sh

    # 配置 Git 用户信息
    - name: Setup Git Configuration
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    # 检出 main 分支并合并临时分支的更改
    - name: Checkout Main Branch and Merge Changes
      run: |
        git checkout main
        git add .
        git commit -m "build"

    # 推送更改到远程 main 分支
    - name: Push Changes to Main Branch
      uses: ad-m/github-push-action@master
      with:
        branch: main
        force: true
        github_token: ${{ secrets.APIHUB_GITHUB_TOKEN }}